### ISSUE TITLE
Weird Runtime Error Cupy

### ISSUE THREAD

**Issue by kc9pos** [evanmayer/effex#10] opened 2022-01-06 05:01 UTC
Hello I am running into an issue I don't know if its something with my environment or dependency issue but I cant seem to fix this error when I try and run your script. 

`python effex.py --time 60 --bandwidth 2.4e6 --frequency 1.4204e9 --num_samp 
262144 --resolution 4096 --gain 29.7 --mode spectrum --loglevel=INFO`

```bash
Found Rafael Micro R820T tuner
Found Rafael Micro R820T tuner
Traceback (most recent call last):
File "effex.py", line 973, in <module>
    loglevel=args.loglevel)
File "effex.py", line 128, in __init__
    self.window = (cusignal.get_window("hamming", self.ntaps * nbins)
File "/home/tszymanski/archiconda3/lib/python3.7/site-packages/cusignal/windows/windows.py", line 2122, in get_window
    return winfunc(*params)
File "/home/tszymanski/archiconda3/lib/python3.7/site-packages/cusignal/windows/windows.py", line 1208, in hamming
    w = _hamming_kernel(size=M)
File "cupy/_core/_kernel.pyx", line 789, in cupy._core._kernel.ElementwiseKernel.__call__
File "cupy/cuda/device.pyx", line 25, in cupy.cuda.device.get_device_id
File "cupy_backends/cuda/api/runtime.pyx", line 289, in cupy_backends.cuda.api.runtime.getDevice
File "cupy_backends/cuda/api/runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
```

Any help would be great before I nuke the SD card and reinstall a new image and try again. I used pip3 install ... for everything. I compiled the drivers for the rtl_sdr which was successful. Thank You

**Comment by evanmayer** [comment] 2022-01-06 05:29
My guess is that it's an issue before my code even has a chance to run, probably something to do with your cuSignal, CuPy, or even CUDA install. The lines

```python
File "cupy/_core/_kernel.pyx", line 789, in cupy._core._kernel.ElementwiseKernel.__call__
File "cupy/cuda/device.pyx", line 25, in cupy.cuda.device.get_device_id
File "cupy_backends/cuda/api/runtime.pyx", line 289, in cupy_backends.cuda.api.runtime.getDevice
File "cupy_backends/cuda/api/runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInitializationError: initialization error
```

suggest it is a problem at the CuPy or CUDA install stage.

Did you follow the [install instructions](https://github.com/evanmayer/effex/blob/master/install_instructions.md) I wrote? These basically refer back to the cuSignal install instructions, which should give you a pretty high chance of success in setting up the environment that `effex` needs. Patching dependencies together manually with `pip` can be a minefield.

If you'd still rather not try a fresh install, to find the root cause, I would work backward, trying each of these until something works or the problem becomes apparent:
* Run my unit tests. From the top level dir of the repo, run `cd effex/; pytest`. I'll bet this throws the same error, though.
* Perform the [cuSignal unit tests](https://github.com/rapidsai/cusignal#source-aarch64-jetson-nano-tk1-tx2-xavier-linux-os) to check that the cuSignal dependency is installed correctly.
* Try to write the simplest code you can think of that uses CuPy, and run that to make sure it works. You should check to see whether or not something like this

```python
import cupy as cp

a = cp.array([0., 1.])
```

throws the same error.

Such a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) will be useful if you go [asking for help](https://en.wikipedia.org/wiki/Wikipedia:Reference_desk/How_to_ask_a_software_question#Example) in the cuSignal, CuPy, or cudatoolkit forums.

**Comment by kc9pos** [comment] 2022-01-09 09:27
Well I am making progress now I receive a error regarding RTL SDR permissions <LIBUSB_ERROR_ACCESS>  (-3) Access Denied  Insufficient Permissions Device index = 0  I seem to be very close any input on how do I give permissions to the device?

**Comment by kc9pos** [comment] 2022-01-09 09:43
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
Traceback (most recent call last):
  File "/home/tszymanski/cusignal/effex/effex/effex.py", line 966, in <module>
    cor = Correlator(run_time=args.run_time,
  File "/home/tszymanski/cusignal/effex/effex/effex.py", line 83, in __init__
    self.sdr0 = RtlSdr(device_index=0, dithering_enabled=False)
  File "/home/tszymanski/miniforge-pypy3/envs/cusignal-dev/lib/python3.9/site-packages/rtlsdr/rtlsdr.py", line 133, in __init__
    self.open(device_index, test_mode_enabled, dithering_enabled, serial_number)
  File "/home/tszymanski/miniforge-pypy3/envs/cusignal-dev/lib/python3.9/site-packages/rtlsdr/rtlsdr.py", line 173, in open
    raise LibUSBError(result, 'Could not open SDR (device index = %d)' % (device_index))
rtlsdr.rtlsdr.LibUSBError: <LIBUSB_ERROR_ACCESS (-3): Access denied (insufficient permissions)> "Could not open SDR (device index = 0)"

**Comment by evanmayer** [comment] 2022-01-09 09:49
Did you follow the [install instructions](https://github.com/evanmayer/effex/blob/master/install_instructions.md) I wrote? The commands I wrote on that page for the compile/install of keenerd’s experimental fork of the `librtlsdr` driver come from [this page](https://www.rtl-sdr.com/rtl-sdr-quick-start-guide/). Thanks for providing the full error message! That’s helpful, because the line that says “Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules” suggests you may have missed a step in those instructions: `sudo cp ../rtl-sdr.rules /etc/udev/rules.d/`. Make sure you didn’t miss any others! I think you are very close now.

**Comment by kc9pos** [comment] 2022-01-09 09:57
good news I rebooted and now I get this error when I run your script cuda driver version insufficient for cuda runtime Ill start i guess upgrading the drivers

**Comment by evanmayer** [comment] 2022-01-09 09:58
If you’re curious how copying this file into the directory is related to device permissions, here is the [manual page](http://manpages.ubuntu.com/manpages/xenial/man7/udev.7.html).

**Comment by evanmayer** [comment] 2022-01-09 10:11
> good news I rebooted and now I get this error when I run your script cuda driver version insufficient for cuda runtime Ill start i guess upgrading the drivers

I wouldn’t necessarily launch right into updating the drivers, in fact, it may be the wrong thing to do. The CUDA Toolkit version installed should be one that is compatible with the GPU hardware on the Jetson Nano. I think NVIDIA helps us accomplish this by something that is hinted at in the [cuSignal install instructions](https://github.com/rapidsai/cusignal#source-aarch64-jetson-nano-tk1-tx2-xavier-linux-os), where they require that you have the correct version of JetPack installed:
> Further, it's assumed that your Jetson device is running a current (>= 4.3) edition of [JetPack](https://developer.nvidia.com/embedded/jetpack) and contains the CUDA Toolkit.

**Comment by kc9pos** [comment] 2022-01-09 16:16
ound Rafael Micro R820T tuner
Found Rafael Micro R820T tuner
Traceback (most recent call last):
  File "/home/tszymanski/cusignal/effex/effex/effex.py", line 966, in <module>
    cor = Correlator(run_time=args.run_time,
  File "/home/tszymanski/cusignal/effex/effex/effex.py", line 128, in __init__
    self.window = (cusignal.get_window("hamming", self.ntaps * nbins)
  File "/home/tszymanski/miniforge-pypy3/envs/cusignal-dev/lib/python3.9/site-packages/cusignal-22.2.0a0+9.g6a02566-py3.9.egg/cusignal/windows/windows.py", line 2122, in get_window
    return winfunc(*params)
  File "/home/tszymanski/miniforge-pypy3/envs/cusignal-dev/lib/python3.9/site-packages/cusignal-22.2.0a0+9.g6a02566-py3.9.egg/cusignal/windows/windows.py", line 1208, in hamming
    w = _hamming_kernel(size=M)
  File "cupy/_core/_kernel.pyx", line 819, in cupy._core._kernel.ElementwiseKernel.__call__
  File "cupy/cuda/device.pyx", line 48, in cupy.cuda.device.get_device_id
  File "cupy_backends/cuda/api/runtime.pyx", line 159, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 132, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version

**Comment by kc9pos** [comment] 2022-01-09 16:25
So that is the error I receive now ill play around with it some more today but yeah I followed all the instructions very carefully 

My board is the latest image 

- CUDA Version 10.2.300
- The toolkit I installed was conda install -c conda-forge cupy cudatoolkit=11.5.0
- NVIDIA Jetson Nano (Developer Kit Version)
 L4T 32.6.1 [ JetPack 4.6 ]
   Ubuntu 18.04.5 LTS
   Kernel Version: 4.9.253-tegra
 CUDA 10.2.300
   CUDA Architecture: 5.3
 OpenCV version: 4.1.1
   OpenCV Cuda: NO
 CUDNN: 8.2.1.32
 TensorRT: 8.0.1.6
 Vision Works: 1.6.0.501
 VPI: ii libnvvpi1 1.1.12 arm64 NVIDIA Vision Programming Interface library
 Vulcan: 1.2.70
Thank You again for all your help

**Comment by evanmayer** [comment] 2022-01-09 17:53
I don’t think you need to do `conda install -c conda-forge cudatoolkit=11.5.0`, I don’t see it in the cuSignal install instructions. 

We are venturing into “installing complicated dependencies by hand” territory, which is really not where you want to be…however, I think the `cudatoolkit` version should agree with the CUDA version on your system. With the conda env active, try `conda remove cudatoolkit` then `conda install cudatoolkit=10.2`, or whatever version matches the CUDA version you have. 

I’m making a lot of guesses here. I will try to go through the process on my own Jetson later today to see if the ease of install has changed since I last tried it.

**Comment by kc9pos** [comment] 2022-01-09 23:13
- So I had to nuke the SD card and reinstall to try again I could not find out the issue as for this attempt I have a fresh install of 
- Jetpack 4.6 
- Ubuntu 18.04 
-  CUDA 10.2.300
- Python3.6.9
As for the instructionsthat I am following  I installed conda-forge/miniforge first. Then followed the instructions to install cusignal using "conda activate cusignal-dev" and created an environment using the instruction at "Source, aarch64 (Jetson Nano, TK1, TX2, Xavier), Linux OS".  Afterwards when that finishes and the I go back to the home directory within the activated environment and start to follow the instructions in your install_instructions.md for "Make a clone of the cusignal env and call it effex-dev, and activate it" now one of my questions is does the environment for cusignal-dev that I installed still run and does it need to be activated to run? because when I go to step 2 in the install_instruction 
"conda create --name effex-dev --clone cusignal-dev" it looks like the cusignal-dev was the environment that was running when I followed the previous instructions at the rapidsai/cusignal page? Once I create the new environment and activate it I finish up the rest of the steps installing the rtl drivers and finish with the "git clone https://github.com/evanmayer/pyrtlsdr.git
cd pyrtlsdr
pip install ./ "

at that point I am not to entirely sure what to do next I go back to my home directory and clone your repo cd into effex/effex and  "run python effex.py --time 60 --bandwidth 2.4e6 --frequency 1.4204e9 --num_samp 262144 --resolution 4096 --gain 29.7 --mode spectrum --loglevel=INFO"

let me know if there is a step im doing wrong or out of place that you can tell from this I will give it a shot again.

**Comment by evanmayer** [comment] 2022-01-09 23:25
>  one of my questions is does the environment for cusignal-dev that I installed still run and does it need to be activated to run? 

After completing the `cusignal` install and cloning the `cusignal-dev` env to make the `effex-dev` env, you do not ever need to invoke `conda activate cusignal-dev` again. You should only need to activate the `effex-dev` environment to run `effex`. (Bootstrapping off of the `cusignal-dev` environment setup is just convenient, because it has ~99% of dependencies we need, and following their install instructions to the letter ensures the `cusignal` dependencies are installed correctly, no matter what changes they make in the future. It makes my life a little easier.) 

> because when I go to step 2 in the install_instruction
`conda create --name effex-dev --clone cusignal-dev` it looks like the cusignal-dev was the environment that was running when I followed the previous instructions at the rapidsai/cusignal page?

Correct.

> at that point I am not to entirely sure what to do next I go back to my home directory and clone your repo cd into effex/effex and run `python effex.py --time 60 --bandwidth 2.4e6 --frequency 1.4204e9 --num_samp 262144 --resolution 4096 --gain 29.7 --mode spectrum --loglevel=INFO`

It sounds like you completed my install instructions. Nice! Do you get any terminal output or error messages after executing that command?

**Comment by kc9pos** [comment] 2022-01-10 02:17
It works im excited thank you for your help. I produced a .csv file of the visibilities my last two questions are how do I graph the .csv file I struggled doing this before with David Lonard FFTs from the fxcorralator he wrote? And also what direction can I take this project in? I am using my 4 channel Kerberos SDR for this project with 4 inverted v dipoles tuned at 144.00Mhz and 440.00Mhz I am looking to make some observations of anything interesting. Currently in Chicago Orion is out? Thank you again for your help with all this.

**Comment by evanmayer** [comment] 2022-01-10 02:31
Great work! 

Unfortunately, I'm not as familiar with David Lonard's work as I'd like to be. As far as plotting goes, I have written a function to graph the contents of the .csv at the end of the observation. It should be getting called automatically at the end of a run. Are you ssh'd into your Jetson, or do you have a keyboard and mouse connected? If you are using ssh, try ssh-ing in with `ssh -X myusername@myjetsonhostname` to [enable X-forwarding](https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely).

That plot will let you look at the raw data recorded, but there's a lot more work (which I have not done yet and depends on a great many other factors) to calibrate/post-process this and turn visibilities into an image. Daniel Estevez does some really nice SDR work, and he wrote about using synchronized SDRs to create an image [using the Allen Telescope Array](https://destevez.net/2021/08/imaging-cygnus-a-at-8-45-ghz-with-ata/). That's where I'd like to go next.

Since there doesn't seem to be an immediate issue with my code, I'll close this issue as resolved. I'm glad you got it working!

**Closed by evanmayer** 2022-01-10 02:31 UTC
